Repository likelion-community/likelion-community-frontend, pull requests merged in 2024-12, with the labels that each got.

#138 [Feature] #125 - 학교 커뮤니티의 질문게시판에 트랙 필터링 드롭다운 추가
  src/components/post/Comments.jsx
  src/pages/mainPostPage/DefaultPostPage.jsx
  src/pages/myPage/MyPostPage.jsx
  src/pages/myPage/MyScrapPage.jsx
  src/pages/schBoardPage/SchQnaBoardPage.jsx
  src/pages/schBoardPage/SchQnaBoardPage.styled.js
  src/pages/schPostPage/QnAPostPage.jsx
Labels: ✨ Feature, 🔗 API, 🛠️ Fix, 🦁 나경

#139 [Fix] #125 - 마이페이지의 내가 쓴 글, 댓글 단 글, 스크랩한 글 에러 수정
  src/components/myPage/MyPagePost.jsx
  src/components/post/Input.jsx
  src/pages/myPage/MyCommentPage.jsx
  src/pages/myPage/MyPostPage.jsx
  src/pages/myPage/MyScrapPage.jsx
Labels: 🔗 API, 🛠️ Fix, 🦁 나경

#140 [Feature] #125 - 채팅 api 연결
  src/components/chat/ChatMember.jsx
  src/components/chat/ChatStart.jsx
  src/components/post/Comments.jsx
  src/components/post/Content.jsx
  src/components/schBoard/SchContent.jsx
  src/pages/chatPage/ChatListPage.jsx
  src/pages/chatPage/ChatListPage.styled.js
  src/pages/chatPage/ChatPage.jsx
  src/pages/chatPage/ChatPage.styled.js
Labels: ✨ Feature, 🔗 API, 🦁 나경

#141 [Fix] #121 - 웰컴페이지 16인치 깨지는거 수정
  src/pages/accountPage/WelcomePage.styled.js
Labels: 🎨 Design, 🛠️ Fix, 🦁 동건
