Repository likelion-community/likelion-community-frontend, pull requests merged in 2024-11, with the labels that each got.

#30 [Feature] #27 - 헤더추가 운영진 출석파일 추가
  src/assets/icons/back.svg
  src/components/Header.jsx
  src/hooks/useCustomNavigate.jsx
  src/layout/DefaultLayout.jsx
  src/pages/adminAttPage/AdminAttManagePage.jsx
  src/pages/adminAttPage/AdminAttManagePage.styled.js
  src/pages/adminAttPage/AdminAttPage.jsx
  src/pages/adminAttPage/AdminAttPage.styled.js
  src/pages/adminAttPage/AdminAttRegisterPage.jsx
  src/pages/adminAttPage/AdminAttRegisterPage.styled.js
  src/pages/loginPage/WelcomePage.jsx
  src/pages/loginPage/WelcomePage.styled.js
  src/router.jsx
  src/styles/theme.js
Labels: ✨ Feature, 🦁 동건

#31 [Feature] #27 - 운영진출석페이지 UI구현
  src/assets/icons/adminPen.svg
  src/assets/icons/cardClose.png
  src/assets/icons/cardOpen.png
  src/assets/icons/dateIcon.svg
  src/assets/icons/dropdown.svg
  src/assets/icons/pingIcon.svg
  src/components/Header.jsx
  src/components/adminAtt/AttCard.jsx
  src/components/adminAtt/AttCard.styled.js
  src/components/adminAtt/Dropdown.jsx
  src/constant/adminAttData.js
  src/pages/adminAttPage/AdminAttPage.jsx
  src/pages/adminAttPage/AdminAttPage.styled.js
  src/styles/theme.js
Labels: ✨ Feature, 🎨 Design, 🦁 동건

#32 [Feature] #29 - 로그인 페이지 UI 구현
  src/assets/icons/eyeClosedToggle.svg
  src/assets/icons/eyeOpenedToggle.svg
  src/assets/icons/id.svg
  src/assets/icons/pw.svg
  src/pages/loginPage/LoginPage.jsx
  src/pages/loginPage/LoginPage.styled.js
  src/pages/loginPage/WelcomePage.jsx
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🦁 선우

#36 [Feature] 출석 코드 입력 페이지 구현
  src/components/MainHeader.jsx
  src/pages/lionAttPage/LionAttNum.jsx
  src/pages/lionAttPage/LionAttNum.styled.js
  src/pages/schMainPage/SchMainPage.jsx
  src/pages/schMainPage/SchMainPage.styled.js
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🦁 나경

#38 [Feature] # 37 - 채팅 페이지 UI 구현
  src/assets/icons/link.svg
  src/assets/icons/send.svg
  src/components/Footer.jsx
  src/components/chat/ChatMember.jsx
  src/pages/chatPage/ChatListPage.jsx
  src/pages/chatPage/ChatListPage.styled.js
  src/pages/chatPage/ChatPage.jsx
  src/pages/chatPage/ChatPage.styled.js
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🦁 나경

#40 [Feature] #39 - 아기사자 출석 정보 확인 페이지 UI 구현
  src/assets/icons/date.svg
  src/assets/icons/image.svg
  src/assets/icons/list.svg
  src/assets/icons/location.svg
  src/pages/lionAttPage/LionAttInfoPage.jsx
  src/pages/lionAttPage/LionAttInfoPage.styled.js
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🦁 나경

#42 [Feature] #27 - 운영진 출석 등록페이지 구현
  src/assets/icons/file.svg
  src/assets/icons/postIcon.svg
  src/components/Header.jsx
  src/components/adminAtt/AttCard.jsx
  src/components/adminAtt/AttCard.styled.js
  src/components/adminAtt/Dropdown.jsx
  src/components/adminAttRegister/AdminAttCode.jsx
  src/components/adminAttRegister/AdminAttPost.jsx
  src/components/adminAttRegister/AdminAttPost.styled.js
  src/components/adminAttRegister/AdminNameCard.jsx
  src/components/adminAttRegister/FileUpload.jsx
  src/components/adminAttRegister/SubmitBtn.jsx
  src/pages/adminAttPage/AdminAttPage.jsx
  src/pages/adminAttPage/AdminAttRegisterPage.jsx
  src/pages/adminAttPage/AdminAttRegisterPage.styled.js
Labels: ✨ Feature, 🎨 Design, 🦁 동건

#43 [Fix] #41 - 아기사자 출석 정보 확인 페이지 사이즈와 버튼 위치 수정
  src/pages/lionAttPage/LionAttInfoPage.jsx
  src/pages/lionAttPage/LionAttInfoPage.styled.js
Labels: 🎨 Design, 🛠️ Fix, 🦁 나경

#49 [Fix] #27 - 드롭다운 경로 대소문자 수정
  src/assets/icons/f5.svg
  src/components/adminAtt/AttCard.jsx
  src/components/adminAttManage/AdminAttInfo.jsx
  src/components/adminAttManage/AdminAttInfo.styled.js
  src/components/adminAttManage/F5Header.jsx
  src/components/adminAttRegister/AdminAttPost.jsx
  src/pages/adminAttPage/AdminAttManagePage.jsx
  src/pages/adminAttPage/AdminAttManagePage.styled.js
  src/pages/adminAttPage/AdminAttPage.jsx
Labels: 🛠️ Fix, 🦁 동건

#51 [Chore] #27 - 버셀 404오류 수정
  vercel.json
Labels: 🛠️ Fix, 🦁 동건

#55 [Feature] #53 - 카카오로그인테스트를 위한 로컬 https설정
  .gitignore
  index.html
  jsconfig.json
  package-lock.json
  package.json
  public/faviconVer2.ico
  src/pages/accountPage/WelcomePage.jsx
  vite.config.js
Labels: 🔗 API, 🦁 동건

#57 [Feature] #54 - 전체 및 학교 커뮤니티의 게시글 작성 페이지 UI 구현
  src/assets/icons/check.svg
  src/assets/icons/photo.svg
  src/components/post/PostingBox.jsx
  src/components/post/PostingBox.styled.js
  src/components/post/PostingBtn.jsx
  src/pages/mainPostingPage/BePostingPage .jsx
  src/pages/mainPostingPage/DefaultPostingPage.jsx
  src/pages/mainPostingPage/FePostingPage.jsx
  src/pages/mainPostingPage/JoinPostingPage.jsx
  src/pages/mainPostingPage/LionPostingPage.jsx
  src/pages/mainPostingPage/NotiPostingPage.jsx
  src/pages/mainPostingPage/PmPostingPage.jsx
  src/pages/mainPostingPage/PostingPage.styled.js
  src/pages/schPostingPage/QnAPostinPage.jsx
  src/pages/schPostingPage/SchDefaultPostingPage.jsx
  src/router.jsx
  vite.config.js
Labels: ✨ Feature, 🎨 Design, 🦁 선우

#61 [Feature] #53 - 카카오로그인, 일반회원가입 아직 구현 덜됨
  src/components/account/LionClass.jsx
  src/components/adminAttRegister/AdminAttPost.jsx
  src/components/adminAttRegister/AdminAttPost.styled.js
  src/pages/accountPage/SignupPage.jsx
  src/pages/accountPage/VerificationPage.jsx
  src/pages/accountPage/WelcomePage.jsx
Labels: 🔗 API, 🦁 동건

#63 [Feature] #62 - 로그인 API연결
  src/pages/accountPage/LoginPage.jsx
Labels: 🔗 API, 🦁 동건

#69 [Feature] #60 - 마이페이지 및 내가 쓴 글 UI 구현
  src/assets/icons/upload.svg
  src/components/myPage/MyPagePost.jsx
  src/components/myPage/MyPagePost.styled.js
  src/constant/myPage/myPostData.js
  src/pages/myPage/MyCommentPage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
  src/pages/myPage/MyPostPage.jsx
  src/pages/myPage/MyPostPage.styled.js
  src/pages/myPage/MyScrapPage.jsx
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🦁 나경

#72 [Feature] #27 - 지각시간 결석시간 입력 추가 구현
  package-lock.json
  package.json
  src/assets/icons/calendar.svg
  src/components/adminAtt/Dropdown.jsx
  src/components/adminAttRegister/AdminAttCode.jsx
  src/components/adminAttRegister/AdminAttPost.jsx
  src/components/adminAttRegister/AdminAttPost.styled.js
  src/components/adminAttRegister/Calendar.jsx
  src/pages/accountPage/LoginPage.jsx
  src/pages/adminAttPage/AdminAttRegisterPage.jsx
Labels: ✨ Feature, 🎨 Design, 🛠️ Fix, 🦁 동건

#77 [Fix] #64 - 카카오로그인구현, 파일명보이게 ui수정
  src/apis/axiosInstance.js
  src/pages/accountPage/KakaoSignupPage.jsx
  src/pages/accountPage/KakaoSignupPage.styled.js
Labels: 🔗 API, 🛠️ Fix, 🦁 동건

#78 [Design] #54 - 게시글 작성 페이지 수정
  package-lock.json
  src/components/account/InputBox.jsx
  src/components/post/PostingBox.styled.js
  src/components/post/PostingBtn.jsx
  src/pages/accountPage/SignupPage.jsx
  src/pages/accountPage/SignupPage.styled.js
  src/pages/mainPostingPage/PostingPage.styled.js
Labels: 🎨 Design, 🦁 선우

#82 [Feature] #81 - 게시글 상세 페이지에 컴포넌트 사용
  src/components/post/Comments.jsx
  src/components/post/Content.jsx
  src/components/post/Content.styled.js
  src/components/post/Input.jsx
  src/pages/mainPostPage/BePostPage.jsx
  src/pages/mainPostPage/DefaultPostPage.jsx
  src/pages/mainPostPage/FePostPage.jsx
  src/pages/mainPostPage/JoinPostPage.jsx
  src/pages/mainPostPage/LionPostPage.jsx
  src/pages/mainPostPage/NotiPostPage.jsx
  src/pages/mainPostPage/PmPostPage.jsx
  src/pages/mainPostPage/PostPage.styled.js
  src/pages/myPage/MyPage.jsx
  src/pages/schPostPage/QnAPostPage.jsx
  src/pages/schPostPage/SchDefaultPostPage.jsx
Labels: ✨ Feature, 🦁 선우

#84 [Fix] #27 -api연결시도 출석페이지 라우터연결 출석등록 props오류수정
  src/apis/axiosInstance.js
  src/components/adminAttManage/AdminAttInfo.jsx
  src/components/adminAttManage/AdminAttInfo.styled.js
  src/components/adminAttManage/AttCard.jsx
  src/components/adminAttManage/AttCodeTimer.jsx
  src/components/adminAttManage/EditDelModal.jsx
  src/components/adminAttRegister/AdminAttPost.jsx
  src/components/adminAttRegister/AdminNameCard.jsx
  src/pages/adminAttPage/AdminAttManagePage.jsx
  src/pages/adminAttPage/AdminAttManagePage.styled.js
  src/pages/adminAttPage/AdminAttRegisterPage.jsx
  src/pages/schMainPage/SchMainPage.jsx
  src/pages/schMainPage/SchMainPage.styled.js
Labels: 🔗 API, 🛠️ Fix, 🦁 동건

#90 [!HOTFIX] #86 - API Csrf토큰 오류 해결을위한 커스텀훅 설정
  src/apis/axiosInstance.js
  src/components/adminAttRegister/AdminAttPost.jsx
  src/components/adminAttRegister/AdminAttPost.styled.js
  src/hooks/useFetchCsrfToken.js
  src/pages/accountPage/KakaoSignupPage.jsx
  src/pages/accountPage/SignupPage.jsx
  src/pages/accountPage/VerificationPage.jsx
  src/pages/adminAttPage/AdminAttPage.jsx
  src/pages/adminAttPage/AdminAttRegisterPage.jsx
  src/pages/myPage/MyPage.jsx
Labels: ✨ Feature, 🔗 API, 🛠️ Fix, 🦁 동건

#92 [Fix] #88 - 아기사자 출석정보디자인수정
  package-lock.json
  src/components/lionAttPage/LionAttInfo.jsx
  src/components/lionAttPage/LionAttTimer.jsx
  src/pages/lionAttPage/LionAttInfoPage.jsx
  src/pages/lionAttPage/LionAttInfoPage.styled.js
  src/pages/lionAttPage/LionAttPage.jsx
  src/pages/lionAttPage/LionAttPage.styled.js
Labels: 🎨 Design, 🛠️ Fix, 🦁 동건

#93 [Feature] - #83 마이페이지 수정
  package-lock.json
  src/pages/accountPage/LoginPage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
  src/pages/myPage/MyPostPage.jsx
Labels: 🔗 API, 🎨 Design, 🦁 선우

#95 [Feature] #86 -운영진 출석페이지 api연결
  src/components/adminAtt/AttCard.jsx
  src/pages/adminAttPage/AdminAttPage.jsx
  src/pages/adminAttPage/AdminAttRegisterPage.jsx
  src/router.jsx
Labels: 🔗 API, 🦁 동건

#96 [Fix] #88 - 아기사자 출석상세 변경된 ui구현
  src/components/lionAttPage/LionAttCard.jsx
  src/components/lionAttPage/LionAttCard.styled.js
  src/pages/adminAttPage/AdminAttPage.jsx
  src/pages/lionAttPage/LionAttInfoPage.styled.js
  src/pages/lionAttPage/LionAttPage.jsx
  src/pages/lionAttPage/LionAttPage.styled.js
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🦁 동건

#98 [Feature] #83 - 내가 쓴 글 페이지 연결
  src/components/myPage/MyPagePost.jsx
  src/components/myPage/MyPagePost.styled.js
  src/components/schBoard/Board.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPostPage.jsx
  src/router.jsx
Labels: 🔗 API, 🦁 선우

#100 [Refactor] #88 - 배포를위한 라우터 대문자수정,출석메인 api연결 isStaff
  src/components/lionAttPage/LionAttCard.styled.js
  src/hooks/useCustomNavigate.jsx
  src/pages/lionAttPage/LionAttPage.jsx
  src/pages/schMainPage/SchMainPage.jsx
Labels: 🔗 API, 🦁 동건

#102 Update favicon.ico with force
  public/favicon.ico
Labels: 🛠️ Fix, 🦁 동건

#106 [Feature] #88 - 아기사자 출석,출석코드입력 수정 에러페이지제작
  src/assets/icons/Error404.svg
  src/main.jsx
  src/pages/accountPage/WelcomePage.jsx
  src/pages/errorPage/ErrorPage.jsx
  src/pages/lionAttPage/LionAttNum.jsx
  src/pages/lionAttPage/LionAttNum.styled.js
  src/pages/lionAttPage/LionAttPage.jsx
  src/pages/lionAttPage/LionAttPage.styled.js
  src/router.jsx
Labels: ✨ Feature, 🔗 API, 🎨 Design, 🛠️ Fix, 🦁 동건

#111 [Feature] #83 - 학교 인증 연결
  src/components/Header.jsx
  src/components/MainHeader.jsx
  src/pages/myPage/MyCommentPage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
Labels: 🔗 API, 🦁 선우

#114 [Feature] #80 - 학교 인증 안 된 경우는 페이지 사용할 수 없도록 구현
  src/assets/icons/lock.svg
  src/components/Footer.jsx
  src/components/MainHeader.jsx
  src/components/mainPage/PopularPost.jsx
  src/components/schBoard/Back.jsx
  src/hooks/userVerification.js
  src/pages/boardPage/DefaultBoardPage.jsx
  src/pages/boardPage/JoinBoardPage.jsx
  src/pages/boardPage/LionBoardPage.jsx
  src/pages/boardPage/NotiBoardPage.jsx
  src/pages/commuPage/CommuMainPage.jsx
  src/pages/mainPage/MainPage.jsx
  src/pages/mainPostPage/DefaultPostPage.jsx
  src/pages/mainPostPage/JoinPostPage.jsx
  src/pages/mainPostPage/LionPostPage.jsx
  src/pages/mainPostPage/NotiPostPage.jsx
  src/pages/schMainPage/SchMainPage.jsx
Labels: ✨ Feature, 🎨 Design, 🦁 나경

#115 [Fix] #80 - 학교 인증 반영되도록 훅 수정
  src/hooks/useUserVerification.js
  src/pages/schMainPage/SchMainPage.jsx
Labels: 🛠️ Fix, 🦁 나경

#117 [Feature] #86 -api들연결
  src/components/Footer.jsx
  src/components/adminAttManage/AdminAttInfo.jsx
  src/components/adminAttRegister/AdminAttPost.jsx
  src/components/lionAttPage/LionAttInfo.jsx
  src/components/lionAttPage/LionAttTimer.jsx
  src/hooks/useCustomNavigate.jsx
  src/pages/adminAttPage/AdminAttManagePage.jsx
  src/pages/adminAttPage/AdminAttPage.jsx
  src/pages/adminAttPage/AdminAttPage.styled.js
  src/pages/adminAttPage/AdminAttRegisterPage.jsx
  src/pages/lionAttPage/LionAttInfoPage.jsx
  src/pages/lionAttPage/LionAttInfoPage.styled.js
  src/pages/lionAttPage/LionAttNum.jsx
  src/pages/lionAttPage/LionAttPage.jsx
  src/pages/schMainPage/SchMainPage.jsx
  src/router.jsx
Labels: ✨ Feature, 🔗 API, 🦁 동건

#126 [Fix] #121 - QA항목들 수정 아기사자출석,운영진출석 등등
  src/components/adminAttManage/AttCodeTimer.jsx
  src/components/adminAttRegister/AdminAttPost.jsx
  src/pages/adminAttPage/AdminAttPage.styled.js
  src/pages/lionAttPage/LionAttInfoPage.jsx
  src/pages/lionAttPage/LionAttPage.jsx
Labels: 🔗 API, 🛠️ Fix, 🦁 동건

#127 [Fix] #83 학교 인증 사진 POST 요청 보내기
  src/components/MainHeader.jsx
  src/components/post/Comments.jsx
  src/components/post/Content.jsx
  src/components/post/Input.jsx
  src/pages/accountPage/SignupPage.styled.js
  src/pages/accountPage/VerificationPage.jsx
  src/pages/accountPage/VerificationPage.styled.js
  src/pages/mainPostPage/DefaultPostPage.jsx
  src/pages/myPage/MyCommentPage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
  src/pages/myPage/MyPostPage.jsx
Labels: 🔗 API, 🦁 선우

#128 [Fix] #121 -일반 로그인 api수정 + 디자인수정
  src/components/MainHeader.jsx
  src/components/adminAttManage/AttCard.jsx
  src/pages/accountPage/WelcomePage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styled.js
Labels: 🔗 API, 🎨 Design, 🛠️ Fix, 🦁 동건

#129 [Fix] #121 - 채팅코드 반영, 채팅 이미지업로드 디자인수정
  src/assets/icons/chatX.svg
  src/pages/chatPage/ChatListPage.jsx
  src/pages/chatPage/ChatPage.jsx
  src/pages/chatPage/ChatPage.styled.js
Labels: 🎨 Design, 🛠️ Fix, 🦁 동건

#130 [Fix] #121 - 채팅 로드될때 스크롤 아래로 오게 수정
  src/pages/chatPage/ChatPage.jsx
Labels: 🛠️ Fix, 🦁 동건

#134 [Fix] #125 - 카카오 로그인 api 수정
  src/pages/accountPage/WelcomePage.jsx
Labels: 🔗 API, 🛠️ Fix, 🦁 나경

#137 [Feature] #125 - 커뮤니티에서 게시글과 댓글 작성자의 사진 보이도록 구현
  src/components/BoardPost.jsx
  src/components/MainHeader.jsx
  src/components/mainPage/PopularPost.jsx
  src/components/myPage/MyPagePost.jsx
  src/components/post/Comments.jsx
  src/components/post/Content.jsx
  src/components/post/Content.styled.js
  src/components/post/PostingBtn.jsx
  src/components/schBoard/BoardInfo.jsx
  src/components/schBoard/SchContent.jsx
  src/pages/mainPostPage/BePostPage.jsx
  src/pages/mainPostPage/DefaultPostPage.jsx
  src/pages/mainPostPage/FePostPage.jsx
  src/pages/mainPostPage/JoinPostPage.jsx
  src/pages/mainPostPage/LionPostPage.jsx
  src/pages/mainPostPage/NotiPostPage.jsx
  src/pages/mainPostPage/PmPostPage.jsx
  src/pages/mainPostingPage/DefaultPostingPage.jsx
  src/pages/mainPostingPage/NotiPostingPage.jsx
  src/pages/schBoardPage/SchAllBoardPage.jsx
  src/pages/schBoardPage/SchNotiBoardPage.jsx
  src/pages/schBoardPage/SchQnaBoardPage.jsx
  src/pages/schPostPage/QnAPostPage.jsx
  src/pages/schPostPage/SchDefaultPostPage.jsx
  src/pages/schPostPage/SchNotiPostPage.jsx
Labels: ✨ Feature, 🦁 나경
